language: python

notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
- pip install --upgrade pip pytest -r requirements.txt
- pip install -e .

script:
- pytest
