language: python

dist: xenial
sudo: require

notifications:
  email:
    on_success: never
    on_failure: never

addons:
  apt:
    packages:
      - gcc-7
      - g++-7

matrix:
  include:
  - python: 3.7
  - python: 3.8
  - python: 3.9

install:
- pip install --upgrade pip pytest -r requirements.txt
- pip install -e .

script:
- pytest
