dist: trusty
language:
  - cpp
  - python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  include:
  - python: 3.7
  - python: 3.8
  - python: 3.9

script:
  - export CC=gcc-7
  - export CXX=g++-7

install:
- pip install --upgrade pip pytest -r requirements.txt
- pip install -e .

script:
- pytest
